config/routes.rb
Rails.application.routes.draw do
  resources :answers

  devise_for :users
  root "questions#new"
  resources :questions do
    resources :answers
  end
  get 'cookies' => 'cookies#index'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  after_initialize :set_default, :if => :new_record?

  def set_default
    self.reviewed = false if self.reviewed.nil?
  end
  belongs_to :user
  has_many :answers

end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :admin, :attorney, :student]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :questions
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = Answer.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    #@answer = Answer.new(answer_params)
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user

    respond_to do |format|
      if @answer.save
        format.html { redirect_to @question, notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:question_id, :body, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_filter :configure_devise_parameters, if: :devise_controller?

  protected
  def configure_devise_parameters
    devise_parameter_sanitizer.for(:sign_up) << :surname
    devise_parameter_sanitizer.for(:account_update) << :surname
  end
end

app/controllers/cookies_controller.rb
class CookiesController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authorize_user, only: [:edit, :update, :destroy] 
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_filter :cache_question, only: [:create]
  before_filter :authenticate_user!, :except => [:new, :index, :show]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
    # @question = current_user.questions.build
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    #@question = Question.new(question_params)
    @question = current_user.questions.build(question_params)
    session[:question_cached] = nil
    respond_to do |format|
      if @question.save
        format.html { redirect_to action: "index" , notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:text,:prize)
    end
    def authorize_user
      @question = current_user.questions.find_by(id: params[:id])
      redirect_to questions_path, notice: "Not authorized" if @question.nil?
    end

    def cache_question
      session[:question_cached] = question_params
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do 
        concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
        concat message 
      end)
    end
    nil
  end
end

app/helpers/cookies_helper.rb
module CookiesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.erb
<%= div_for(answer) do %>
    <div class="answer_wrapper clearfix">
    <div class="pull-left">
      <p class="lead"><%= answer.body %></p>
      <p><small>Submitted <strong><%= time_ago_in_words(answer.created_at) %> ago</strong> by <%= answer.user.email %></small></p>
    </div>
        <div class="btn-group pull-right">
          <% if answer.user == current_user -%>
              <%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-default" %>
          <% end %>
        </div>
      </div>
    <% end %>

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :question_id %><br>
    <%= f.number_field :question_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.question_id %></td>
        <td><%= answer.body %></td>
        <td><%= answer.user %></td>
        <td><%= link_to 'Show', answer %></td>
        <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
        <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @answer.question_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @answer.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @answer.user %>
</p>

<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/cookies/index.html.erb
<h2>COOKIES</h2>
<p>Cookies are small text files which are downloaded to your computer, tablet or mobile phone when you visit a website or application. The website or application may retrieve these cookies from your web browser (eg Internet Explorer, Mozilla Firefox or Google Chrome) each time you visit, so they can recognise you, remember your preferences and provide you with a more secure online experience.</p>
<p>Generally, cookies are very useful and are a common method used by almost every website you visit because they help to make your online experience as smooth as possible. For security reasons, many websites will not function at all without the use of cookies (or other similar technologies, such as "web beacons" or "tags").</p>
<p>Cookies generally do not hold any information to identify an individual person, but are instead used to identify a browser on an individual machine.</p>
<p>If you prefer, you can restrict, block or delete cookies by changing your browser settings but that may mean that the website won't work properly</p>
<p>For more information about cookies and their impact on you and your browsing visit <a href="http://www.aboutcookies.org">www.aboutcookies.org</a>.</p>
<h2>TYPES OF COOKIES</h2>
<h3>Necessary cookies</h3>
<p>These cookies are essential in helping you to make use of the features and services we offer on the Brainwer website. Without these cookies, the services you want to use cannot be provided. These cookies do not gather information about you that could be used to identify you, and they do not monitor or remember where you have been on the internet.</p>
<h3>Functional cookies</h3>
<p>These cookies allow us to provide you with a better online experience when you use our website. They do not gather or store any information which would allow us to identify you personally.</p>
<h3>Performance cookies</h3>
<p>Performance cookies help us to understand how our customers use our site, so we can keep our products and services relevant, easy to use and up to date. For example, we can see which products and services are most popular, identify when and where errors occur, and test different versions of a page in order to provide an improved online experience.</p>
<p>Sometimes, the services we use to collect this information may be operated by other companies on our behalf. They may use similar technologies to cookies, known as "web beacons" or "tags". These are anonymous and, as they are only used for statistical purposes, they do not contain or collect any information that identifies you.</p>
<h3>Targeting cookies</h3>
<p>We have relationships with carefully selected and monitored suppliers (third parties) who may also set cookies during your visit. The purpose of these cookies is "behavioural advertising" (also known as "behavioural targeting" or "remarketing"), which is a means of showing you relevant products and services based on what you appear to be interested in. Although these cookies can track your visits around the web they don't know who you are. Without these cookies, online advertisements you encounter will be less relevant to you and your interests.</p>
<h2>MANAGING COOKIES</h2>
<p>Most internet browsers allow you to erase cookies from your computer hard drive, block all cookies (or just third-party cookies) or warn you before a cookie is stored on your device.</p>
<p>Please note, if you choose to block all cookies, our site will not function as intended and you will not be able to use or access many of the services we provide. If you have blocked all cookies and wish to make full use of the features and services we offer, you will need to enable your cookies. You can do this in your browser (see below).</p>
<p>Rather than blocking all cookies, you can choose to only block third-party cookies which will still allow our website to function as intended.</p>
<h3>How to manage cookies on your PC</h3>
<p>To enable cookies on our website, follow the steps below.</p>
<h4>Google Chrome</h4>
<ol>
  <li>Click "Tools" at the top of your browser and select "Settings".</li>
  <li>Click "Show advanced settings", scroll down to the section "Privacy" and click "Content Settings."</li>
  <li>Select "Allow local data to be set". To only acept first-party cookies, check the box next to "Block all third-party cookies without exception"</li>
</ol>
<h4>Microsoft Internet Explorer 6.0, 7.0, 8.0, 9.0</h4>
<ol>
  <li>Click "Tools" at the top of your browser and select "Internet Options", then click the "Privacy" tab.</li>
  <li>Check that the level of your privacy is set to Medium or lower, which will allow the use of cookies in your browser.</li>
  <li>If set above medium level it will prevent the use of cookies.</li>
</ol>
<h4>Mozilla Firefox</h4>
<ol>
  <li>Click "Tools" at the top of your browser and select "Options".</li>
  <li>Then select the "Privacy" icon.</li>
  <li>Click the "Cookies" and select "Allow pages to create a cookie."</li>
</ol>
<h4>Safari</h4>
<ol>
  <li>Click the gear icon at the top of your browser and select "Settings".</li>
  <li>Click the "Privacy" tab, then select the option "Disable the use of cookies by third parties and advertising cookies."</li>
  <li>Click "Save".</li>
</ol>
<h3>How to manage cookies on your Mac</h3>
<p>To enable cookies on our website, follow the steps below.</p>
<h4>Microsoft Internet Explorer 5.0 on OSX</h4>
<ol>
  <li>Click on "Explorer" at the top of your browser and select "Settings".</li>
  <li>Scroll down to the "Cookies" section in the "Received Files".</li>
  <li>Select "Do not ask."</li>
</ol>
<h4>Safari on OSX</h4>
<ol>
  <li>Click "Safari" on the top of your browser and select "Settings".</li>
  <li>Click the "Privacy" and then "Enable cookies."</li>
  <li>Select "only the pages you have visited."</li>
</ol>
<h4>Mozilla and Netscape on OSX</h4>
<ol>
  <li>Click "Mozilla" or "Netscape" at the top of your browser and select "Settings".</li>
  <li>Scroll down to the "Cookies" under "Privacy & Security".</li>
  <li>Select "Allow cookies only to the original site."</li>
</ol>
<h4>Opera</h4>
<ol>
  <li>Click "Menu" on the top of your browser and select "Settings".</li>
  <li>Then select "Options" tab and the "Advanced".</li>
 <li>Select "Enable cookies."</li>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>BrainwerWebapp</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="navbar-header">
    <h3 class="muted"><%= link_to "Brainwer", root_path, class:"nounderline"  %></h3>
  </div>
  <% if user_signed_in? %>
    <ul class="nav navbar-nav pull-right">
    <li><%= link_to 'Il tuo account', edit_user_registration_path %></li>
    <li><%= link_to 'Esci', destroy_user_session_path, :method => :delete %></li>
  </ul>
<% else %>
    <ul class="nav navbar-nav pull-right">
    <li><%= link_to 'Registrati', new_user_registration_path %></li>
    <li><%= link_to 'Entra', new_user_session_path %></li>
  </ul>
<% end %>
</nav>
<div class="container">
  <div class="row">
    <div class="col-xs-4">
    </div>
    <div class="col-xs-3">
      <%= flash_messages %>
    </div>
    <div class="col-xs-5">
    </div>
  </div>
  <%= yield %>
</div>

</body>
</html>

app/views/questions/_form.html.erb
<%= bootstrap_form_for(@question) do |f| %>
  <% if @question.errors.any? %>
  <div id="error_explanation">
  <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

  <ul>
    <% @question.errors.full_messages.each do |message| %>
      <li><%= message %></li>
  <% end %>
  </ul>
</div>
  <% end %>
<div class="field">
  <% text = session[:question_cached]["text"] unless session[:question_cached].nil?  %>
  <% prize = session[:question_cached]["prize"] unless session[:question_cached].nil?  %>
  <%= f.text_area :text,hide_label:true,  placeholder:"Esempio..",:value => text , rows: 7%><br>
  <div class="input-group form-inline">
    <%= f.number_field :prize,  :class => 'text_field', :step => 'any',placeholder:100, min:0, style: "width:150px",prepend: "€",  label: "Quanto vuoi offrire? ", :value => prize %>
    <%= f.primary "Invia", class:"btn-lg" %>
  </div>
</div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% @questions.each do |question| %>
    <% if current_user && current_user.admin? || question.user == current_user %>
    <tr>
    <td><%= question.text %></td>
    <td><%= question.prize %></td>
    <td><%= link_to 'Show', question %></td>
      <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>
  </tr>
<% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<%= render 'cookies_eu/cookies_eu', link: '/cookies'  %>
<div class="page-header centered">
  <h1>Fai la tua domanda <small>I migliori giustisti ti risponderanno</small></h1>
</div>
<div class="row" >
  <div class="col-md-2">
  </div>
  <div class="col-md-8">
<%= render 'form' %>
  </div>
  <div class="col-md-2">
  </div>
</div>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Text:</strong>
  <%= @question.text %><br/>
  <strong>Price</strong>
  <%= @question.prize %>
</p>
<h3><%= @question.answers.count  %> Answers</h3>
<div id="answers">
  <%= render :partial => @question.answers %>
</div>
<% if signed_in? && @question.user != current_user %>
<%= simple_form_for [@question, Answer.new] do |f| %>
  <div class="field">
    <%= f.text_area :body, class: "form-control"  %>
  </div>
  <br />
  <%= f.submit "Add Answer", class: "btn-primary btn" %>
<% end %>
<% end %>
<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>